language: node_js
node_js: '8'
before_script: npm install
jobs:
  fast_finish: true
  include:
    - stage: check formatting issues
      script:
        - |
          npm run compile
    - stage: run linter
      script:
        - |
          npm run lint
    - stage: check token issues
      script:
        - |
          npm run test:checkToken
    - stage: check contract issues
      script:
        - |
          npm run test:checkContract
    - stage: check nft issues
      script:
        - |
          npm run test:checkNft
